apiVersion: v1
kind: Service
metadata:
  labels:
    app: rancher
  name: rancher
spec:
  type: NodePort
  ports:
    - port: 80
      name: rancher
      targetPort: 8080
      protocol: TCP
  selector:
    app: rancher
